//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIKeyConfig) DeepCopyInto(out *APIKeyConfig) {
	*out = *in
	if in.AutoManage != nil {
		in, out := &in.AutoManage, &out.AutoManage
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIKeyConfig.
func (in *APIKeyConfig) DeepCopy() *APIKeyConfig {
	if in == nil {
		return nil
	}
	out := new(APIKeyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DERPConfig) DeepCopyInto(out *DERPConfig) {
	*out = *in
	in.Server.DeepCopyInto(&out.Server)
	if in.URLs != nil {
		in, out := &in.URLs, &out.URLs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Paths != nil {
		in, out := &in.Paths, &out.Paths
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AutoUpdateEnabled != nil {
		in, out := &in.AutoUpdateEnabled, &out.AutoUpdateEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DERPConfig.
func (in *DERPConfig) DeepCopy() *DERPConfig {
	if in == nil {
		return nil
	}
	out := new(DERPConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DERPServerConfig) DeepCopyInto(out *DERPServerConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.VerifyClients != nil {
		in, out := &in.VerifyClients, &out.VerifyClients
		*out = new(bool)
		**out = **in
	}
	if in.AutomaticallyAddEmbeddedDerpRegion != nil {
		in, out := &in.AutomaticallyAddEmbeddedDerpRegion, &out.AutomaticallyAddEmbeddedDerpRegion
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DERPServerConfig.
func (in *DERPServerConfig) DeepCopy() *DERPServerConfig {
	if in == nil {
		return nil
	}
	out := new(DERPServerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSConfig) DeepCopyInto(out *DNSConfig) {
	*out = *in
	if in.MagicDNS != nil {
		in, out := &in.MagicDNS, &out.MagicDNS
		*out = new(bool)
		**out = **in
	}
	if in.OverrideLocalDNS != nil {
		in, out := &in.OverrideLocalDNS, &out.OverrideLocalDNS
		*out = new(bool)
		**out = **in
	}
	in.Nameservers.DeepCopyInto(&out.Nameservers)
	if in.SearchDomains != nil {
		in, out := &in.SearchDomains, &out.SearchDomains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExtraRecords != nil {
		in, out := &in.ExtraRecords, &out.ExtraRecords
		*out = make([]DNSExtraRecord, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSConfig.
func (in *DNSConfig) DeepCopy() *DNSConfig {
	if in == nil {
		return nil
	}
	out := new(DNSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSExtraRecord) DeepCopyInto(out *DNSExtraRecord) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSExtraRecord.
func (in *DNSExtraRecord) DeepCopy() *DNSExtraRecord {
	if in == nil {
		return nil
	}
	out := new(DNSExtraRecord)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSNameserversConfig) DeepCopyInto(out *DNSNameserversConfig) {
	*out = *in
	if in.Global != nil {
		in, out := &in.Global, &out.Global
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Split != nil {
		in, out := &in.Split, &out.Split
		*out = make(map[string][]string, len(*in))
		for key, val := range *in {
			var outVal []string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSNameserversConfig.
func (in *DNSNameserversConfig) DeepCopy() *DNSNameserversConfig {
	if in == nil {
		return nil
	}
	out := new(DNSNameserversConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseConfig) DeepCopyInto(out *DatabaseConfig) {
	*out = *in
	if in.Debug != nil {
		in, out := &in.Debug, &out.Debug
		*out = new(bool)
		**out = **in
	}
	in.Gorm.DeepCopyInto(&out.Gorm)
	in.Sqlite.DeepCopyInto(&out.Sqlite)
	in.Postgres.DeepCopyInto(&out.Postgres)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseConfig.
func (in *DatabaseConfig) DeepCopy() *DatabaseConfig {
	if in == nil {
		return nil
	}
	out := new(DatabaseConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GormConfig) DeepCopyInto(out *GormConfig) {
	*out = *in
	if in.PrepareStmt != nil {
		in, out := &in.PrepareStmt, &out.PrepareStmt
		*out = new(bool)
		**out = **in
	}
	if in.ParameterizedQueries != nil {
		in, out := &in.ParameterizedQueries, &out.ParameterizedQueries
		*out = new(bool)
		**out = **in
	}
	if in.SkipErrRecordNotFound != nil {
		in, out := &in.SkipErrRecordNotFound, &out.SkipErrRecordNotFound
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GormConfig.
func (in *GormConfig) DeepCopy() *GormConfig {
	if in == nil {
		return nil
	}
	out := new(GormConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Headscale) DeepCopyInto(out *Headscale) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Headscale.
func (in *Headscale) DeepCopy() *Headscale {
	if in == nil {
		return nil
	}
	out := new(Headscale)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Headscale) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeadscaleConfig) DeepCopyInto(out *HeadscaleConfig) {
	*out = *in
	if in.GRPCAllowInsecure != nil {
		in, out := &in.GRPCAllowInsecure, &out.GRPCAllowInsecure
		*out = new(bool)
		**out = **in
	}
	out.Noise = in.Noise
	out.Prefixes = in.Prefixes
	in.DERP.DeepCopyInto(&out.DERP)
	if in.DisableCheckUpdates != nil {
		in, out := &in.DisableCheckUpdates, &out.DisableCheckUpdates
		*out = new(bool)
		**out = **in
	}
	in.Database.DeepCopyInto(&out.Database)
	out.Log = in.Log
	out.Policy = in.Policy
	in.DNS.DeepCopyInto(&out.DNS)
	in.OIDC.DeepCopyInto(&out.OIDC)
	in.LogTail.DeepCopyInto(&out.LogTail)
	if in.RandomizeClientPort != nil {
		in, out := &in.RandomizeClientPort, &out.RandomizeClientPort
		*out = new(bool)
		**out = **in
	}
	in.Taildrop.DeepCopyInto(&out.Taildrop)
	in.Tuning.DeepCopyInto(&out.Tuning)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeadscaleConfig.
func (in *HeadscaleConfig) DeepCopy() *HeadscaleConfig {
	if in == nil {
		return nil
	}
	out := new(HeadscaleConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeadscaleList) DeepCopyInto(out *HeadscaleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Headscale, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeadscaleList.
func (in *HeadscaleList) DeepCopy() *HeadscaleList {
	if in == nil {
		return nil
	}
	out := new(HeadscaleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HeadscaleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeadscalePreAuthKey) DeepCopyInto(out *HeadscalePreAuthKey) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeadscalePreAuthKey.
func (in *HeadscalePreAuthKey) DeepCopy() *HeadscalePreAuthKey {
	if in == nil {
		return nil
	}
	out := new(HeadscalePreAuthKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HeadscalePreAuthKey) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeadscalePreAuthKeyList) DeepCopyInto(out *HeadscalePreAuthKeyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HeadscalePreAuthKey, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeadscalePreAuthKeyList.
func (in *HeadscalePreAuthKeyList) DeepCopy() *HeadscalePreAuthKeyList {
	if in == nil {
		return nil
	}
	out := new(HeadscalePreAuthKeyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HeadscalePreAuthKeyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeadscalePreAuthKeySpec) DeepCopyInto(out *HeadscalePreAuthKeySpec) {
	*out = *in
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeadscalePreAuthKeySpec.
func (in *HeadscalePreAuthKeySpec) DeepCopy() *HeadscalePreAuthKeySpec {
	if in == nil {
		return nil
	}
	out := new(HeadscalePreAuthKeySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeadscalePreAuthKeyStatus) DeepCopyInto(out *HeadscalePreAuthKeyStatus) {
	*out = *in
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeadscalePreAuthKeyStatus.
func (in *HeadscalePreAuthKeyStatus) DeepCopy() *HeadscalePreAuthKeyStatus {
	if in == nil {
		return nil
	}
	out := new(HeadscalePreAuthKeyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeadscaleSpec) DeepCopyInto(out *HeadscaleSpec) {
	*out = *in
	in.Config.DeepCopyInto(&out.Config)
	in.PersistentVolumeClaim.DeepCopyInto(&out.PersistentVolumeClaim)
	in.APIKey.DeepCopyInto(&out.APIKey)
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeadscaleSpec.
func (in *HeadscaleSpec) DeepCopy() *HeadscaleSpec {
	if in == nil {
		return nil
	}
	out := new(HeadscaleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeadscaleStatus) DeepCopyInto(out *HeadscaleStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeadscaleStatus.
func (in *HeadscaleStatus) DeepCopy() *HeadscaleStatus {
	if in == nil {
		return nil
	}
	out := new(HeadscaleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeadscaleUser) DeepCopyInto(out *HeadscaleUser) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeadscaleUser.
func (in *HeadscaleUser) DeepCopy() *HeadscaleUser {
	if in == nil {
		return nil
	}
	out := new(HeadscaleUser)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HeadscaleUser) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeadscaleUserList) DeepCopyInto(out *HeadscaleUserList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HeadscaleUser, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeadscaleUserList.
func (in *HeadscaleUserList) DeepCopy() *HeadscaleUserList {
	if in == nil {
		return nil
	}
	out := new(HeadscaleUserList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HeadscaleUserList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeadscaleUserSpec) DeepCopyInto(out *HeadscaleUserSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeadscaleUserSpec.
func (in *HeadscaleUserSpec) DeepCopy() *HeadscaleUserSpec {
	if in == nil {
		return nil
	}
	out := new(HeadscaleUserSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeadscaleUserStatus) DeepCopyInto(out *HeadscaleUserStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeadscaleUserStatus.
func (in *HeadscaleUserStatus) DeepCopy() *HeadscaleUserStatus {
	if in == nil {
		return nil
	}
	out := new(HeadscaleUserStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogConfig) DeepCopyInto(out *LogConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogConfig.
func (in *LogConfig) DeepCopy() *LogConfig {
	if in == nil {
		return nil
	}
	out := new(LogConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogTailConfig) DeepCopyInto(out *LogTailConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogTailConfig.
func (in *LogTailConfig) DeepCopy() *LogTailConfig {
	if in == nil {
		return nil
	}
	out := new(LogTailConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NoiseConfig) DeepCopyInto(out *NoiseConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NoiseConfig.
func (in *NoiseConfig) DeepCopy() *NoiseConfig {
	if in == nil {
		return nil
	}
	out := new(NoiseConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OIDCConfig) DeepCopyInto(out *OIDCConfig) {
	*out = *in
	if in.OnlyStartIfOIDCIsAvailable != nil {
		in, out := &in.OnlyStartIfOIDCIsAvailable, &out.OnlyStartIfOIDCIsAvailable
		*out = new(bool)
		**out = **in
	}
	if in.UseExpiryFromToken != nil {
		in, out := &in.UseExpiryFromToken, &out.UseExpiryFromToken
		*out = new(bool)
		**out = **in
	}
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExtraParams != nil {
		in, out := &in.ExtraParams, &out.ExtraParams
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.AllowedDomains != nil {
		in, out := &in.AllowedDomains, &out.AllowedDomains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedUsers != nil {
		in, out := &in.AllowedUsers, &out.AllowedUsers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedGroups != nil {
		in, out := &in.AllowedGroups, &out.AllowedGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.PKCE.DeepCopyInto(&out.PKCE)
	if in.EmailVerifiedRequired != nil {
		in, out := &in.EmailVerifiedRequired, &out.EmailVerifiedRequired
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OIDCConfig.
func (in *OIDCConfig) DeepCopy() *OIDCConfig {
	if in == nil {
		return nil
	}
	out := new(OIDCConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PKCEConfig) DeepCopyInto(out *PKCEConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PKCEConfig.
func (in *PKCEConfig) DeepCopy() *PKCEConfig {
	if in == nil {
		return nil
	}
	out := new(PKCEConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersistentVolumeClaimConfig) DeepCopyInto(out *PersistentVolumeClaimConfig) {
	*out = *in
	if in.Size != nil {
		in, out := &in.Size, &out.Size
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.StorageClassName != nil {
		in, out := &in.StorageClassName, &out.StorageClassName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersistentVolumeClaimConfig.
func (in *PersistentVolumeClaimConfig) DeepCopy() *PersistentVolumeClaimConfig {
	if in == nil {
		return nil
	}
	out := new(PersistentVolumeClaimConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyConfig) DeepCopyInto(out *PolicyConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyConfig.
func (in *PolicyConfig) DeepCopy() *PolicyConfig {
	if in == nil {
		return nil
	}
	out := new(PolicyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresConfig) DeepCopyInto(out *PostgresConfig) {
	*out = *in
	if in.SSL != nil {
		in, out := &in.SSL, &out.SSL
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresConfig.
func (in *PostgresConfig) DeepCopy() *PostgresConfig {
	if in == nil {
		return nil
	}
	out := new(PostgresConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrefixesConfig) DeepCopyInto(out *PrefixesConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrefixesConfig.
func (in *PrefixesConfig) DeepCopy() *PrefixesConfig {
	if in == nil {
		return nil
	}
	out := new(PrefixesConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SqliteConfig) DeepCopyInto(out *SqliteConfig) {
	*out = *in
	if in.WriteAheadLog != nil {
		in, out := &in.WriteAheadLog, &out.WriteAheadLog
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SqliteConfig.
func (in *SqliteConfig) DeepCopy() *SqliteConfig {
	if in == nil {
		return nil
	}
	out := new(SqliteConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSConfig) DeepCopyInto(out *TLSConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSConfig.
func (in *TLSConfig) DeepCopy() *TLSConfig {
	if in == nil {
		return nil
	}
	out := new(TLSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaildropConfig) DeepCopyInto(out *TaildropConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaildropConfig.
func (in *TaildropConfig) DeepCopy() *TaildropConfig {
	if in == nil {
		return nil
	}
	out := new(TaildropConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tuning) DeepCopyInto(out *Tuning) {
	*out = *in
	if in.NotifierSendTimeout != nil {
		in, out := &in.NotifierSendTimeout, &out.NotifierSendTimeout
		*out = new(string)
		**out = **in
	}
	if in.BatchChangeDelay != nil {
		in, out := &in.BatchChangeDelay, &out.BatchChangeDelay
		*out = new(string)
		**out = **in
	}
	if in.NodeMapSessionBufferedChanSize != nil {
		in, out := &in.NodeMapSessionBufferedChanSize, &out.NodeMapSessionBufferedChanSize
		*out = new(int)
		**out = **in
	}
	if in.BatcherWorkers != nil {
		in, out := &in.BatcherWorkers, &out.BatcherWorkers
		*out = new(int)
		**out = **in
	}
	if in.RegisterCacheCleanup != nil {
		in, out := &in.RegisterCacheCleanup, &out.RegisterCacheCleanup
		*out = new(string)
		**out = **in
	}
	if in.RegisterCacheExpiration != nil {
		in, out := &in.RegisterCacheExpiration, &out.RegisterCacheExpiration
		*out = new(string)
		**out = **in
	}
	if in.NodeStoreBatchSize != nil {
		in, out := &in.NodeStoreBatchSize, &out.NodeStoreBatchSize
		*out = new(int)
		**out = **in
	}
	if in.NodeStoreBatchTimeout != nil {
		in, out := &in.NodeStoreBatchTimeout, &out.NodeStoreBatchTimeout
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tuning.
func (in *Tuning) DeepCopy() *Tuning {
	if in == nil {
		return nil
	}
	out := new(Tuning)
	in.DeepCopyInto(out)
	return out
}
